---
# Enable Karmab maister repo
- name: Enable kcli COPR repository
  dnf:
    name: "karmab/kcli"
    state: present
  become: true

# Install dnf packages
- name: Install required packages
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - kcli
    - bash-completion
    - vim
    - jq
    - tar
    - git
    - ipcalc
    - python3-pyOpenSSL
    - dnsmasq
    - policycoreutils-python-utils

- name: Create temporary directory for download
  file:
    path: "/tmp/openshift-client"
    state: directory
  become: true
  
- name: Download OpenShift Client archive
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ocp_version}}/openshift-client-linux-{{ocp_version}}.tar.gz"
    dest: "/tmp/openshift-client/openshift-client-linux-{{ocp_version}}.tar.gz"
  become: true
  
- name: Extract OpenShift Client archive
  unarchive:
    src: "/tmp/openshift-client/openshift-client-linux-{{ocp_version}}.tar.gz"
    dest: "/tmp/openshift-client"
    remote_src: true
  become: true

- name: Copy OpenShift Client binary to /usr/local/bin
  copy:
    src: "/tmp/openshift-client/{{ item }}"
    dest: "/usr/bin/"
    mode: "0755"
  become: true
  loop:
    - oc
    - kubectl

- name: Clean up temporary directory
  file:
    path: "/tmp/openshift-client"
    state: absent
  become: true


#- name: Create network using kcli
#  command: "kcli create network -c 192.168.125.0/24 --nodhcp --domain 5g-deployment.lab 5gdeploymentlab"
#  become: true

- name: Create 5G Deployment Network
  virt_net:
    state: defined
    name: 5gdeploymentlab
    bridge: virbr0  # Adjust the bridge name as per your setup
    cidr: 192.168.125.0/24
    dhcp: no
    domain: 5g-deployment.lab
  delegate_to: localhost
  become: true

- name: Configure dnsmasq
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop:
    - { src: "files/dnsmasq.conf", dest: "/opt/dnsmasq/dnsmasq.conf" }
    - { src: "files/upstream-resolv.conf", dest: "/opt/dnsmasq/upstream-resolv.conf" }
    - { src: "files/hub.ipv4", dest: "/opt/dnsmasq/include.d/hub.ipv4" }
    - { src: "files/sno1.ipv4", dest: "/opt/dnsmasq/include.d/sno1.ipv4" }
    - { src: "files/sno2.ipv4", dest: "/opt/dnsmasq/include.d/sno2.ipv4" }
    - { src: "files/infrastructure-host.ipv4", dest: "/opt/dnsmasq/include.d/infrastructure-host.ipv4" }
    - { src: "files/dnsmasq-virt.service", dest: "/etc/systemd/system/dnsmasq-virt.service" }

- name: Create and manage hosts.leases file
  file:
    path: /opt/dnsmasq/hosts.leases
    state: touch
  become: yes
  
- name: Set SELinux context for hosts.leases
  sefcontext:
    target: /opt/dnsmasq/hosts.leases
    setype: dnsmasq_lease_t
    state: present
  become: yes

- name: Restore SELinux context for hosts.leases
  sefcontext:
    target: /opt/dnsmasq/hosts.leases
    setype: system_u:object_r:dnsmasq_lease_t:s0
    state: restorecon
  become: yes
  
- name: Update upstream DNS in upstream-resolv.conf
  replace:
    path: "/opt/dnsmasq/upstream-resolv.conf"
    regexp: "UPSTREAM_DNS"
    replace: "1.1.1.1"
  become: true

- name: Enable and start dnsmasq-virt service
  systemd:
    name: dnsmasq-virt
    enabled: yes
    daemon_reload: yes
    state: started
  become: true

- name: Mask dnsmasq service
  systemd:
    name: dnsmasq
    masked: yes
  become: true
