---
- name: Configure webcache for hosts with hub label
  hosts: "{{ webcache_hosts | default('localhost') }}"
  become: true
  tasks:
    - name: Copy podman-webcache.service file
      ansible.builtin.copy:
        src: podman-webcache.service
        dest: /etc/systemd/system/podman-webcache.service

    - name: Create /opt/webcache/data directory
      ansible.builtin.file:
        path: /opt/webcache/data
        state: directory

    - name: Download rhcos-4.13.0-x86_64-live-rootfs.x86_64.img
      ansible.builtin.get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.13/4.13.0/rhcos-4.13.0-x86_64-live-rootfs.x86_64.img"
        dest: "/opt/webcache/data/rhcos-4.13.0-x86_64-live-rootfs.x86_64.img"

    - name: Download rhcos-4.13.0-x86_64-live.x86_64.iso
      ansible.builtin.get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.13/4.13.0/rhcos-4.13.0-x86_64-live.x86_64.iso"
        dest: "/opt/webcache/data/rhcos-4.13.0-x86_64-live.x86_64.iso"

    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start podman-webcache service
      ansible.builtin.systemd:
        name: podman-webcache
        enabled: yes
        state: started
